# Generated by Django 4.2.3 on 2024-02-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('sent_to_customer', 'Sent to Customer'), ('paid', 'Paid')], default='draft', max_length=30, verbose_name='Status'),
        ),
    ]
