# Generated by Django 4.2.3 on 2024-02-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_management', '0002_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('sent_to_customer', 'Sent to Customer'), ('paid', 'Paid')], default='draft', max_length=30, verbose_name='Status'),
        ),
    ]
