# Generated by Django 4.2.3 on 2024-01-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0025_user_is_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-id'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
    ]
