# Generated by Django 4.2.3 on 2023-10-04 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0003_stwrequirements_remove_stwimage_stw_id_delete_stw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='STWDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('description', models.TextField()),
                ('reference_number', models.CharField(max_length=50, null=True)),
                ('rectification_description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('executed', 'Executed')], default='pending', max_length=30)),
                ('defect_type', models.CharField(choices=[('actual_defect', 'Actual Defect'), ('recommended', 'Recommended Defect')], default='actual_defect', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_planning_management.stwrequirements')),
            ],
            options={
                'verbose_name': 'STW Defect',
                'verbose_name_plural': 'STW Defect',
            },
        ),
        migrations.CreateModel(
            name='STWDefectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_path', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('defect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_planning_management.stwdefect')),
                ('stw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_planning_management.stwrequirements')),
            ],
            options={
                'verbose_name': 'STW Defect Document',
                'verbose_name_plural': 'STW Defect Document',
            },
        ),
        migrations.CreateModel(
            name='STWAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_path', models.CharField(max_length=256)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_planning_management.stwrequirements')),
            ],
            options={
                'verbose_name': 'STW Action Document',
                'verbose_name_plural': 'STW Action Document',
            },
        ),
    ]
