# Generated by Django 4.2.3 on 2023-10-09 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0034_remove_soritem_validity'),
        ('work_planning_management', '0005_stwdefect_sor_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirement_management.quotation')),
            ],
        ),
    ]
