# Generated by Django 4.2.3 on 2023-10-17 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0006_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='STWJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_planning_management.stwrequirements')),
            ],
        ),
    ]
