# Generated by Django 4.2.3 on 2023-10-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0006_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='stwrequirements',
            name='building_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stwrequirements',
            name='postcode',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
