# Generated by Django 4.2.3 on 2023-10-12 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0006_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='RLOLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('site_address_info', models.TextField(null=True)),
                ('company_info', models.TextField(null=True)),
                ('main_content_block', models.TextField(null=True)),
                ('complete_template', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RLO Letter Template',
                'verbose_name_plural': 'RLO Letter Templates',
            },
        ),
        migrations.CreateModel(
            name='RLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('edited_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work_planning_management.rlolettertemplate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_planning_management.job')),
            ],
            options={
                'verbose_name': 'RLO',
                'verbose_name_plural': 'RLO',
            },
        ),
    ]
