# Generated by Django 4.2.3 on 2023-10-12 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_planning_management', '0007_rlolettertemplate_rlo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rlo',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rlo_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
