# Generated by Django 4.2.3 on 2023-10-13 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0007_sitepackdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepackdocument',
            name='document_path',
        ),
        migrations.AddField(
            model_name='sitepackdocument',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SitepackAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_path', models.CharField(max_length=256)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sitepack_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_planning_management.stwrequirements')),
            ],
            options={
                'verbose_name': 'Sitepack Document',
                'verbose_name_plural': 'Sitepack Document',
            },
        ),
    ]
