# Generated by Django 4.2.3 on 2023-10-13 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0008_remove_sitepackdocument_document_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitepackasset',
            options={'verbose_name': 'Sitepack Asset', 'verbose_name_plural': 'Sitepack Asset'},
        ),
        migrations.AlterField(
            model_name='sitepackasset',
            name='sitepack_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_planning_management.sitepackdocument'),
        ),
    ]
