# Generated by Django 4.2.3 on 2023-10-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0007_stwrequirements_building_name_and_more'),
        ('work_planning_management', '0008_rlo_user_id'),
    ]

    operations = [
    ]
