# Generated by Django 4.2.3 on 2023-10-18 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0007_stwjob'),
        ('work_planning_management', '0009_alter_sitepackasset_options_and_more'),
        ('work_planning_management', '0009_merge_20231017_1131'),
    ]

    operations = [
    ]
