# Generated by Django 4.2.3 on 2023-10-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0010_merge_20231018_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('trade_type', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.AlterModelOptions(
            name='stwjob',
            options={'verbose_name': 'STW Job', 'verbose_name_plural': 'STW Job'},
        ),
        migrations.RemoveField(
            model_name='rlolettertemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rlolettertemplate',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(to='work_planning_management.member')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
