# Generated by Django 4.2.3 on 2023-10-18 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0013_remove_member_created_at_remove_member_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepackasset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sitepackasset',
            name='updated_at',
        ),
    ]
