# Generated by Django 4.2.3 on 2023-10-18 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0015_member_created_at_member_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitepackasset',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
