# Generated by Django 4.2.3 on 2023-10-18 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0016_rename_created_at_sitepackasset_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='updated_at',
        ),
    ]
