# Generated by Django 4.2.3 on 2023-10-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0017_remove_member_created_at_remove_member_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
