# Generated by Django 4.2.3 on 2023-10-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0020_stwjobassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stwjobassignment',
            name='assigned_to_member',
        ),
        migrations.AddField(
            model_name='stwjobassignment',
            name='assigned_to_member',
            field=models.ManyToManyField(to='work_planning_management.member'),
        ),
    ]
