# Generated by Django 4.2.3 on 2023-10-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0021_remove_stwjobassignment_assigned_to_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_planning_management.job')),
                ('sitepack_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_planning_management.sitepackasset')),
            ],
            options={
                'verbose_name': 'Job Document',
                'verbose_name_plural': 'Job Documents',
            },
        ),
    ]
