# Generated by Django 4.2.3 on 2023-10-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0023_jobdocument_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdocument',
            name='customer_id',
        ),
    ]
