# Generated by Django 4.2.3 on 2023-10-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0025_stwjobassignment_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stwjobassignment',
            name='event',
        ),
    ]
