# Generated by Django 4.2.3 on 2023-10-30 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('work_planning_management', '0026_remove_stwjobassignment_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='stwjobassignment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.event'),
        ),
    ]
