# Generated by Django 4.2.3 on 2023-11-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0028_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stwjobassignment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_planning_management.events'),
        ),
    ]
