# Generated by Django 4.2.3 on 2023-11-08 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0029_alter_stwjobassignment_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='work_planning_management.member'),
        ),
        migrations.AddField(
            model_name='events',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_planning_management.team'),
        ),
    ]
