# Generated by Django 4.2.3 on 2024-01-08 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0032_alter_events_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stwjobassignment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_planning_management.events'),
        ),
    ]
