# Generated by Django 4.2.3 on 2024-01-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0033_stwjobassignment_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='members',
            field=models.ManyToManyField(blank=True, to='work_planning_management.member'),
        ),
    ]
