# Generated by Django 4.2.3 on 2024-02-06 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0045_alter_report_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_planning_management', '0034_alter_events_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Site Pack Name')),
                ('orignal_document_name', models.CharField(max_length=256, null=True, verbose_name='Site Pack Document')),
                ('document_path', models.CharField(max_length=256, verbose_name='Site Pack Path')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_pack_user', to=settings.AUTH_USER_MODEL, verbose_name='Site Pack USer')),
            ],
            options={
                'verbose_name': 'Site Pack',
                'verbose_name_plural': 'Site Packs',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='sitepackasset',
            name='sitepack_id',
        ),
        migrations.RemoveField(
            model_name='stwjob',
            name='stw',
        ),
        migrations.RemoveField(
            model_name='stwjobassignment',
            name='assigned_to_member',
        ),
        migrations.RemoveField(
            model_name='stwjobassignment',
            name='assigned_to_team',
        ),
        migrations.RemoveField(
            model_name='stwjobassignment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='stwjobassignment',
            name='stw_job',
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_to_member',
            field=models.ManyToManyField(to='work_planning_management.member'),
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_to_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_planning_management.team'),
        ),
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_planning_management.events'),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='stw',
            field=models.ManyToManyField(to='work_planning_management.stwrequirements', verbose_name='STW Quotation'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='quotation',
        ),
        migrations.DeleteModel(
            name='SitepackDocument',
        ),
        migrations.DeleteModel(
            name='STWJob',
        ),
        migrations.DeleteModel(
            name='STWJobAssignment',
        ),
        migrations.AddField(
            model_name='job',
            name='quotation',
            field=models.ManyToManyField(to='requirement_management.quotation', verbose_name='Quotation'),
        ),
        migrations.AlterField(
            model_name='jobdocument',
            name='sitepack_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_planning_management.sitepack'),
        ),
        migrations.DeleteModel(
            name='SitepackAsset',
        ),
    ]
