# Generated by Django 4.2.3 on 2024-01-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0035_sitepack_remove_sitepackasset_sitepack_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
