# Generated by Django 4.2.3 on 2024-02-06 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_planning_management', '0035_sitepack_remove_sitepackasset_sitepack_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
