# Generated by Django 4.2.3 on 2024-02-06 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0037_job_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepack',
            name='orignal_document_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Site Pack Document'),
        ),
    ]
