# Generated by Django 4.2.3 on 2024-02-05 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_planning_management', '0037_job_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepack',
            name='orignal_document_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Site Pack Document'),
        ),
        migrations.AlterField(
            model_name='sitepack',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='sitepack',
            name='document_path',
            field=models.CharField(max_length=256, verbose_name='Site Pack Path'),
        ),
        migrations.AlterField(
            model_name='sitepack',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Site Pack Name'),
        ),
        migrations.AlterField(
            model_name='sitepack',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='sitepack',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_pack_user', to=settings.AUTH_USER_MODEL, verbose_name='Site Pack USer'),
        ),
    ]
