# Generated by Django 4.2.3 on 2024-02-08 10:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0038_job_end_date_job_event_job_start_date_job_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stwdefect',
            name='action',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='stwdefect',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='stwdefect',
            name='rectification_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='stwrequirements',
            name='action',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='stwrequirements',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
