# Generated by Django 4.2.3 on 2024-03-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_planning_management', '0039_alter_stwdefect_action_alter_stwdefect_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=30),
        ),
    ]
