# Generated by Django 4.2.3 on 2023-08-04 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='city',
            new_name='town',
        ),
    ]
