# Generated by Django 4.2.3 on 2023-07-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_conversationtype_contact_created_by_conversation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_by',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='document',
            new_name='document_path',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='summary',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='created_by',
            new_name='user_id',
        ),
    ]
