# Generated by Django 4.2.3 on 2023-08-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_city_contact_town'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='company',
            new_name='company_name',
        ),
    ]
