# Generated by Django 4.2.3 on 2023-11-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_first_name_alter_contact_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mobile_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
