# Generated by Django 4.2.3 on 2023-07-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_remove_contact_state_contact_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='pincode',
            new_name='post_code',
        ),
    ]
