# Generated by Django 4.2.3 on 2023-07-22 11:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_rename_pincode_contact_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
