# Generated by Django 4.2.3 on 2023-07-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'permissions': (('list_todo', 'Can list Todo'),)},
        ),
    ]
