# Generated by Django 4.2.3 on 2023-07-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'permissions': (('list_todo', 'Can list Todo'),)},
        ),
    ]
