# Generated by Django 4.2.3 on 2023-09-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='pending', help_text='The status of the comment.', max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='completed_at',
            field=models.DateField(blank=True, help_text='The date when the to-do item was completed.', null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='Low', help_text='The priority of the to-do item.', max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='pending', help_text='The status of the to-do item.', max_length=20),
        ),
    ]
