# Generated by Django 4.2.3 on 2023-07-24 10:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
