# Generated by Django 4.2.3 on 2023-10-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_comment_status_alter_todo_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
