# Generated by Django 4.2.3 on 2023-08-04 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0002_remove_billingaddress_tax_exepmt_and_more'),
        ('requirement_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='site_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_management.siteaddress'),
        ),
    ]
