# Generated by Django 4.2.3 on 2023-08-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0002_requirement_site_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='document_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
