# Generated by Django 4.2.3 on 2023-08-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0003_requirement_document_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='UPRN',
            field=models.CharField(max_length=12),
        ),
    ]
