# Generated by Django 4.2.3 on 2023-08-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0004_alter_requirement_uprn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='UPRN',
        ),
        migrations.AddField(
            model_name='requirementdefect',
            name='UPRN',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
