# Generated by Django 4.2.3 on 2023-08-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0005_remove_requirement_uprn_requirementdefect_uprn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='quality_surveyor',
            new_name='quantity_surveyor',
        ),
    ]
