# Generated by Django 4.2.3 on 2023-08-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0006_rename_quality_surveyor_requirement_quantity_surveyor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'verbose_name': 'Fire Risk Assessment', 'verbose_name_plural': 'Fire Risk Assessment'},
        ),
    ]
