# Generated by Django 4.2.3 on 2023-08-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0007_alter_requirement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirementdefect',
            options={'verbose_name': 'Fire Risk Assessment Defect', 'verbose_name_plural': 'Fire Risk Assessment Defect'},
        ),
        migrations.AlterModelOptions(
            name='requirementdocument',
            options={'verbose_name': 'Fire Risk Assessment Defect Document', 'verbose_name_plural': 'Fire Risk Assessment Defect Document'},
        ),
    ]
