# Generated by Django 4.2.3 on 2023-08-17 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirement_management', '0008_alter_requirementdefect_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='surveyor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveyor', to=settings.AUTH_USER_MODEL),
        ),
    ]
