# Generated by Django 4.2.3 on 2023-08-17 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0009_requirement_surveyor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='document_path',
        ),
        migrations.CreateModel(
            name='RequirementAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_path', models.CharField(max_length=256)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirement_management.requirement')),
            ],
            options={
                'verbose_name': 'Fire Risk Assessment Document',
                'verbose_name_plural': 'Fire Risk Assessment Document',
            },
        ),
    ]
