# Generated by Django 4.2.3 on 2023-08-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0011_requirementdefectresponse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirementdefectresponse',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='requirementdefectresponseimage',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='requirementdocument',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='requirementdefectresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='requirementdefectresponseimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
