# Generated by Django 4.2.3 on 2023-08-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0012_rename_create_at_requirementdefectresponse_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='reference_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
