# Generated by Django 4.2.3 on 2023-08-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0013_requirementdefect_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementdefect',
            name='action',
            field=models.TextField(max_length=1000),
        ),
    ]
