# Generated by Django 4.2.3 on 2023-09-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0015_rename_requirementdocument_requirementdefectdocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('to-surveyor', 'To Surveyor'), ('assigned-to-surveyor ', 'Assigned To Surveyor')], default='pending', max_length=30),
        ),
    ]
