# Generated by Django 4.2.3 on 2023-09-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0016_alter_requirement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementdefect',
            name='defect_period',
        ),
        migrations.RemoveField(
            model_name='requirementdefect',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('to-surveyor', 'To Surveyor'), ('assigned-to-surveyor ', 'Assigned To Surveyor')], default='active', max_length=30),
        ),
    ]
