# Generated by Django 4.2.3 on 2023-09-07 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0017_remove_requirementdefect_defect_period_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'verbose_name': 'FRA Action', 'verbose_name_plural': 'FRA Action'},
        ),
        migrations.AlterModelOptions(
            name='requirementasset',
            options={'verbose_name': 'FRA Action Document', 'verbose_name_plural': 'FRA Action Document'},
        ),
        migrations.AlterField(
            model_name='requirementdefect',
            name='action',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='requirementdefect',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_path', models.CharField(max_length=500, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('defect_id', models.ManyToManyField(blank=True, to='requirement_management.requirementdefect')),
                ('requirement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirement_management.requirement')),
            ],
        ),
    ]
