# Generated by Django 4.2.3 on 2023-09-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0019_report_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf_path',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
