# Generated by Django 4.2.3 on 2023-09-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0020_report_pdf_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'submitted')], default='draft', max_length=30),
        ),
    ]
