# Generated by Django 4.2.3 on 2023-09-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0021_report_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementdefect',
            name='UPRN',
        ),
        migrations.AddField(
            model_name='requirement',
            name='RBNO',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='UPRN',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
