# Generated by Django 4.2.3 on 2023-09-14 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0022_remove_requirementdefect_uprn_requirement_rbno_and_more'),
        ('requirement_management', '0022_sor_sorimage'),
    ]

    operations = [
    ]
