# Generated by Django 4.2.3 on 2023-09-14 04:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0011_remove_item_item_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirement_management', '0023_merge_20230914_0427'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SOR',
            new_name='SORItem',
        ),
        migrations.RenameModel(
            old_name='SORImage',
            new_name='SORItemImage',
        ),
    ]
