# Generated by Django 4.2.3 on 2023-09-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0025_soritem_user_id_sorcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorcategory',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
