# Generated by Django 4.2.3 on 2023-09-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0026_alter_sorcategory_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementdefect',
            name='defect_type',
            field=models.CharField(choices=[('actual_defect', 'Actual Defect'), ('recommended', 'Recommended Defect')], default='actual_defect', max_length=30),
        ),
    ]
