# Generated by Django 4.2.3 on 2023-09-16 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirement_management', '0027_requirementdefect_defect_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submit', 'submitted')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='soritem',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_json', models.JSONField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_quotations', to=settings.AUTH_USER_MODEL)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='requirement_management.report')),
                ('requirement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='requirement_management.requirement')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_quotations', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
    ]
