# Generated by Django 4.2.3 on 2023-09-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0028_alter_report_status_alter_soritem_name_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
