# Generated by Django 4.2.3 on 2023-09-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0029_quotation_submitted_at_quotation_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
