# Generated by Django 4.2.3 on 2023-09-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0030_quotation_pdf_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='defect_id',
            field=models.ManyToManyField(blank=True, to='requirement_management.requirementdefect'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('send_for_approval', 'Send For Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
    ]
