# Generated by Django 4.2.3 on 2023-09-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0031_quotation_defect_id_alter_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='soritem',
            name='units',
            field=models.CharField(choices=[('no', 'No'), ('week', 'Week'), ('sqm', 'SqM'), ('lm', 'LM'), ('unit', 'Unit')], default='no', max_length=20),
        ),
    ]
