# Generated by Django 4.2.3 on 2023-09-28 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0006_sorvalidity'),
        ('requirement_management', '0032_soritem_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='soritem',
            name='validity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common_app.sorvalidity'),
        ),
    ]
