# Generated by Django 4.2.3 on 2023-11-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0034_remove_soritem_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='due_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
