# Generated by Django 4.2.3 on 2023-12-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0036_alter_requirement_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['-id'], 'verbose_name': 'FRA Action', 'verbose_name_plural': 'FRA Action'},
        ),
        migrations.AlterModelOptions(
            name='requirementdefect',
            options={'ordering': ['-id'], 'verbose_name': 'Fire Risk Assessment Defect', 'verbose_name_plural': 'Fire Risk Assessment Defect'},
        ),
        migrations.AlterModelOptions(
            name='sorcategory',
            options={'ordering': ['-id']},
        ),
    ]
