# Generated by Django 4.2.3 on 2024-01-17 08:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0037_alter_quotation_options_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='action',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
