# Generated by Django 4.2.3 on 2024-01-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0037_alter_quotation_options_alter_report_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SORItemProxy',
            fields=[
            ],
            options={
                'verbose_name': 'DefaultSORItem',
                'verbose_name_plural': 'DefaultSORItem',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('requirement_management.soritem',),
        ),
    ]
