# Generated by Django 4.2.3 on 2024-01-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0038_alter_requirement_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='survey_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='survey_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
