# Generated by Django 4.2.3 on 2024-01-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0038_soritemproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soritemproxy',
            options={'verbose_name': 'Default SOR Item', 'verbose_name_plural': 'Default SOR Item'},
        ),
    ]
