# Generated by Django 4.2.3 on 2024-01-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0039_requirement_survey_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('to-surveyor', 'To Surveyor'), ('assigned-to-surveyor', 'Assigned To Surveyor')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='survey_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='survey_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
