# Generated by Django 4.2.3 on 2024-01-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0040_alter_requirement_status_and_more'),
        ('requirement_management', '0040_alter_soritem_customer_id'),
    ]

    operations = [
    ]
