# Generated by Django 4.2.3 on 2024-01-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0041_merge_20240119_0717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sorcategory',
            options={'ordering': ['-id'], 'verbose_name': 'SOR Category', 'verbose_name_plural': 'SOR Category'},
        ),
        migrations.AlterModelOptions(
            name='soritemproxy',
            options={'verbose_name': 'SOR Item', 'verbose_name_plural': 'SOR Item'},
        ),
    ]
