# Generated by Django 4.2.3 on 2024-01-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0042_alter_sorcategory_options_alter_soritemproxy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sorcategory',
            options={'verbose_name': 'SOR Category', 'verbose_name_plural': 'SOR Category'},
        ),
        migrations.AlterModelOptions(
            name='soritemproxy',
            options={'verbose_name': 'SOR Item', 'verbose_name_plural': 'SOR Items'},
        ),
    ]
