# Generated by Django 4.2.3 on 2024-01-22 12:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0044_alter_requirementdefect_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comments',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
