# Generated by Django 4.2.3 on 2024-03-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0045_alter_report_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('to-survey', 'To Survey'), ('assigned-to-surveyor', 'Assigned To Surveyor')], default='to-survey', max_length=30),
        ),
    ]
