# Generated by Django 4.2.3 on 2024-03-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_management', '0047_alter_requirement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('quoted', 'Quoted'), ('awaiting-approval', 'Awaiting Approval'), ('to-commence', 'To Commence'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
    ]
