# Generated by Django 4.2.3 on 2023-07-27 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='UserRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('contact', 'contact')], max_length=100)),
                ('can_list_data', models.BooleanField()),
                ('can_create_data', models.BooleanField()),
                ('can_change_data', models.BooleanField()),
                ('can_view_data', models.BooleanField()),
                ('can_delete_data', models.BooleanField()),
                ('access_list_data', models.CharField(choices=[('self', 'Self'), ('all', 'All')], max_length=100)),
                ('access_change_data', models.CharField(choices=[('self', 'Self'), ('all', 'All')], max_length=100)),
                ('access_view_data', models.CharField(choices=[('self', 'Self'), ('all', 'All')], max_length=100)),
                ('access_delete_data', models.CharField(choices=[('self', 'Self'), ('all', 'All')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userrole')),
            ],
        ),
    ]
