# Generated by Django 4.2.3 on 2023-07-27 07:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userrole_created_at_userrole_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='can_manage_permission',
        ),
        migrations.RemoveField(
            model_name='userrolepermission',
            name='access_change_data',
        ),
        migrations.RemoveField(
            model_name='userrolepermission',
            name='access_delete_data',
        ),
        migrations.RemoveField(
            model_name='userrolepermission',
            name='access_list_data',
        ),
        migrations.RemoveField(
            model_name='userrolepermission',
            name='access_view_data',
        ),
        migrations.AlterField(
            model_name='userrole',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='userrolepermission',
            name='can_change_data',
            field=models.CharField(choices=[('self', 'Self'), ('all', 'All'), ('none', 'None')], max_length=100, verbose_name='Change'),
        ),
        migrations.AlterField(
            model_name='userrolepermission',
            name='can_create_data',
            field=models.BooleanField(verbose_name='Create'),
        ),
        migrations.AlterField(
            model_name='userrolepermission',
            name='can_delete_data',
            field=models.CharField(choices=[('self', 'Self'), ('all', 'All'), ('none', 'None')], max_length=100, verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='userrolepermission',
            name='can_list_data',
            field=models.CharField(choices=[('self', 'Self'), ('all', 'All'), ('none', 'None')], max_length=100, verbose_name='List'),
        ),
        migrations.AlterField(
            model_name='userrolepermission',
            name='can_view_data',
            field=models.CharField(choices=[('self', 'Self'), ('all', 'All'), ('none', 'None')], max_length=100, verbose_name='View'),
        ),
    ]
