# Generated by Django 4.2.3 on 2023-07-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_state_user_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pincode',
            new_name='post_code',
        ),
    ]
