# Generated by Django 4.2.3 on 2023-07-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_userrole_can_manage_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolepermission',
            name='can_change_data',
            field=models.CharField(choices=[('self', 'Self'), ('all', 'All'), ('none', 'None')], default='self', max_length=100, verbose_name='Change'),
        ),
        migrations.AlterField(
            model_name='userrolepermission',
            name='can_delete_data',
            field=models.CharField(choices=[('self', 'Self'), ('all', 'All'), ('none', 'None')], default='self', max_length=100, verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='userrolepermission',
            name='can_list_data',
            field=models.CharField(choices=[('self', 'Self'), ('all', 'All'), ('none', 'None')], default='self', max_length=100, verbose_name='List'),
        ),
        migrations.AlterField(
            model_name='userrolepermission',
            name='can_view_data',
            field=models.CharField(choices=[('self', 'Self'), ('all', 'All'), ('none', 'None')], default='self', max_length=100, verbose_name='View'),
        ),
        migrations.AlterUniqueTogether(
            name='userrolepermission',
            unique_together={('role', 'module')},
        ),
    ]
