# Generated by Django 4.2.3 on 2023-07-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_userrolepermission_can_change_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='authentication.userrole', verbose_name='UserRole'),
        ),
        migrations.AlterField(
            model_name='userrolepermission',
            name='module',
            field=models.CharField(choices=[('contact', 'Contact'), ('costumer', 'Costumer')], max_length=100),
        ),
    ]
