# Generated by Django 4.2.3 on 2023-08-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_roles_alter_userrolepermission_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolepermission',
            name='module',
            field=models.CharField(choices=[('contact', 'Contacts'), ('todo', 'ToDo'), ('customer', 'Customer'), ('requirement', 'Requirement'), ('survey', 'Survey (Scheduling)'), ('stock_management', 'Stock Management'), ('invoicing', 'Invoicing')], max_length=100),
        ),
    ]
