# Generated by Django 4.2.3 on 2023-08-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_roles_alter_userrolepermission_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='customer_type',
            field=models.CharField(choices=[('business', 'Business'), ('individual', 'Individual')], default='individual', max_length=10),
        ),
        migrations.AlterField(
            model_name='userrolepermission',
            name='module',
            field=models.CharField(choices=[('contact', 'Contacts'), ('todo', 'ToDo'), ('customer', 'Customer'), ('requirement', 'Requirement'), ('survey', 'Survey (Scheduling)'), ('stock_management', 'Stock Management'), ('invoicing', 'Invoicing')], max_length=100),
        ),
    ]
