# Generated by Django 4.2.3 on 2023-08-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_user_city_user_town'),
        ('authentication', '0009_user_created_by'),
    ]

    operations = [
    ]
