# Generated by Django 4.2.3 on 2023-08-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_merge_20230804_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enforce_login',
            field=models.BooleanField(default=False),
        ),
    ]
