# Generated by Django 4.2.3 on 2023-08-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_enforce_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='enforce_login',
            new_name='enforce_password_change',
        ),
    ]
