# Generated by Django 4.2.3 on 2023-08-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolepermission',
            name='module',
            field=models.CharField(choices=[('contact', 'Contacts'), ('todo', 'ToDo'), ('customer', 'Customer'), ('fire_risk_assessment', 'Fire Risk Assessment'), ('survey', 'Survey (Scheduling)'), ('stock_management', 'Stock Management'), ('invoicing', 'Invoicing')], max_length=100),
        ),
    ]
