# Generated by Django 4.2.3 on 2023-08-19 17:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_userrolepermission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(choices=[('Customer', 'Customer'), ('contractor', 'Contractor'), ('sale_executive', 'Sale Executive'), ('quantity_surveyor', 'Quantity Surveyor'), ('surveyor', 'Surveyor'), ('estimator', 'Estimator'), ('project_manager/contract_manager', 'Project Manager/Contract Manager'), ('projects_coordinator', 'Projects Coordinator'), ('projects_RLO', 'Projects RLO'), ('financial_manager', 'Financial Manager'), ('projects_admin_(IT)', 'Projects Admin (IT)'), ('supervisor', 'Supervisor'), ('snagging_supervisor', 'Snagging Supervisor'), ('quality_assurance', 'Quality Assurance'), ('sub-contractor', 'Sub-Contractor')], max_length=100, unique=True),
        ),
    ]
