# Generated by Django 4.2.3 on 2023-08-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_userrolepermission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolepermission',
            name='module',
            field=models.CharField(choices=[('contact', 'Contacts'), ('todo', 'ToDo'), ('customer', 'Customer'), ('fire_risk_assessment', 'Fire Risk Assessment'), ('survey', 'Survey (Scheduling)'), ('stock_management', 'Stock Management'), ('purchase_order', 'Purchase Order'), ('invoicing', 'Invoicing')], max_length=100),
        ),
    ]
