# Generated by Django 4.2.3 on 2023-08-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_userrolepermission_module'),
        ('authentication', '0017_alter_userrolepermission_module'),
    ]

    operations = [
    ]
