# Generated by Django 4.2.3 on 2024-01-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_user_is_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
    ]
