# Generated by Django 4.2.3 on 2024-02-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_user_is_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer_type',
            field=models.CharField(choices=[('public sector-NHS', 'Public Sector-NHS'), ('public Sector-social housing', 'Public Sector-Social Housing'), ('private Sector-social housing', 'Private Sector-Social Housing'), ('facilities management', 'Facilities Management'), ('commercial client', 'Commercial Client'), ('private client', 'Private Client')], default='public sector-NHS', max_length=100),
        ),
    ]
