# Generated by Django 4.2.3 on 2023-08-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='permissions',
        ),
    ]
