# Generated by Django 4.2.3 on 2023-08-08 17:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0002_remove_menuitem_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('recipient', models.EmailField(max_length=254)),
                ('content', ckeditor.fields.RichTextField()),
                ('purpose', models.CharField(choices=[('new_user_registration', 'New User Registration')], max_length=50, unique=True)),
            ],
        ),
    ]
