# Generated by Django 4.2.3 on 2023-09-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0004_emailnotificationtemplate_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
            ],
        ),
    ]
