# Generated by Django 4.2.3 on 2023-08-18 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('invoice_pdf_path', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.TextField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_order_management.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderReceivedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_inventory', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_order_management.purchaseorderinvoice')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_order_management.purchaseorderitem')),
            ],
        ),
    ]
