# Generated by Django 4.2.3 on 2023-08-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0003_rename_invoice_id_purchaseorderinvoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderreceivedinventory',
            name='received_inventory',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
