# Generated by Django 4.2.3 on 2023-08-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0004_alter_purchaseorderreceivedinventory_received_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderinvoice',
            old_name='purchase_order',
            new_name='purchase_order_id',
        ),
        migrations.RenameField(
            model_name='purchaseorderreceivedinventory',
            old_name='purchase_order_invoice',
            new_name='purchase_order_invoice_id',
        ),
        migrations.RenameField(
            model_name='purchaseorderreceivedinventory',
            old_name='purchase_order_item',
            new_name='purchase_order_item_id',
        ),
    ]
