# Generated by Django 4.2.3 on 2023-08-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0005_rename_purchase_order_purchaseorderinvoice_purchase_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent_for_approval', 'Sent for Approval'), ('approved', 'Approved'), ('partially_completed', 'Partially completed'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
