# Generated by Django 4.2.3 on 2023-09-06 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0006_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='order_date',
        ),
    ]
