# Generated by Django 4.2.3 on 2023-12-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0007_remove_purchaseorder_due_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderreceivedinventory',
            options={'ordering': ['id']},
        ),
    ]
