# Generated by Django 4.2.3 on 2024-01-10 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0014_alter_inventorylocation_address_and_more'),
        ('customer_management', '0005_alter_siteaddress_country_alter_siteaddress_county_and_more'),
        ('purchase_order_management', '0008_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='location_type',
            field=models.CharField(choices=[('site address', 'Site Address'), ('warehouse', 'Warehouse')], default='warehouse', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='site_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_management.siteaddress'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='inventory_location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_management.inventorylocation'),
        ),
    ]
