# Generated by Django 4.2.3 on 2024-01-04 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0005_alter_siteaddress_country_alter_siteaddress_county_and_more'),
        ('purchase_order_management', '0008_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='site_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer_management.siteaddress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
