# Generated by Django 4.2.3 on 2024-01-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0009_purchaseorder_site_address_purchaseorder_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='location_type',
            field=models.CharField(choices=[('site address', 'Site Address'), ('warehouse', 'Warehouse')], default='warehouse', max_length=20),
        ),
    ]
