# Generated by Django 4.2.3 on 2024-02-22 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0015_inventory_site_address_and_more'),
        ('work_planning_management', '0039_alter_stwdefect_action_alter_stwdefect_description_and_more'),
        ('contact', '0006_alter_contact_country_alter_contact_county_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_order_management', '0010_purchaseorder_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='job_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_planning_management.job'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_for',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('sub_contractor', 'Sub-Contractor')], default='vendor', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sub_contractor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='item_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_management.item'),
        ),
    ]
