# Generated by Django 4.2.3 on 2024-01-08 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0005_alter_siteaddress_country_alter_siteaddress_county_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_order_management', '0011_alter_purchaseorder_site_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='site_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_management.siteaddress', verbose_name='Customer Site address'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
    ]
