# Generated by Django 4.2.3 on 2024-02-22 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0015_inventory_site_address_and_more'),
        ('purchase_order_management', '0011_purchaseorder_job_id_purchaseorder_po_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_management.vendor'),
        ),
    ]
