# Generated by Django 4.2.3 on 2024-01-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0012_alter_purchaseorder_site_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='site_address',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='user_id',
        ),
    ]
