# Generated by Django 4.2.3 on 2024-02-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order_management', '0013_purchaseorder_po_date_purchaseorder_po_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
