# Generated by Django 4.2.3 on 2024-01-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0014_alter_inventorylocation_address_and_more'),
        ('purchase_order_management', '0014_purchaseorder_location_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='inventory_location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_management.inventorylocation'),
        ),
    ]
