# Generated by Django 4.2.3 on 2023-08-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='tax_exepmt',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='tax_preference',
            field=models.CharField(blank=True, choices=[('taxable', 'Taxable'), ('tax_exempt', 'Tax Exempt')], max_length=20, null=True),
        ),
    ]
