# Generated by Django 4.2.3 on 2023-08-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0002_remove_billingaddress_tax_exepmt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='pan_number',
        ),
    ]
