# Generated by Django 4.2.3 on 2023-12-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0003_remove_billingaddress_pan_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contactperson',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='siteaddress',
            options={'ordering': ['id']},
        ),
    ]
