# Generated by Django 4.2.3 on 2024-02-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0005_alter_siteaddress_country_alter_siteaddress_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='contact_name',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='contact_tel_no',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('30 days', '30 Days'), ('45 days', '45 Days'), ('60 days', '60 Days')], max_length=20, null=True),
        ),
    ]
