# Generated by Django 4.2.3 on 2024-02-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0006_billingaddress_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='purchase_order_required',
            field=models.BooleanField(default=False, help_text='Tick the box for Yes, leave it unchecked for No.', verbose_name='Is a Purchase Order number required?'),
        ),
    ]
