# Generated by Django 4.2.3 on 2024-02-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0007_billingaddress_purchase_order_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='purchase_order_required',
            field=models.BooleanField(default=True, verbose_name='Is a Purchase Order number required?'),
        ),
    ]
