# Generated by Django 4.2.3 on 2024-02-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0008_alter_billingaddress_purchase_order_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='job_role',
            field=models.TextField(max_length=254, null=True),
        ),
    ]
