# Generated by Django 4.2.3 on 2024-02-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0009_contactperson_job_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteaddress',
            name='UPRN',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
