# Generated by Django 4.2.3 on 2024-02-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0010_siteaddress_uprn'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='CIS',
            field=models.BooleanField(default=True),
        ),
    ]
