# Generated by Django 4.2.3 on 2024-02-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0011_billingaddress_cis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='siteaddress',
            name='user_id',
        ),
    ]
