# Generated by Django 4.2.3 on 2024-02-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0014_alter_contactperson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermeta',
            name='utr_number',
            field=models.CharField(max_length=255, null=True, verbose_name='UTR Number'),
        ),
    ]
