# Generated by Django 4.2.3 on 2024-02-27 13:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0015_alter_customermeta_utr_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customermeta',
            unique_together={('user_id', 'company_name')},
        ),
    ]
