# Generated by Django 4.2.3 on 2023-08-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0004_item_item_type_vendor_billing_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sku',
            new_name='reference_number',
        ),
        migrations.AddField(
            model_name='item',
            name='units',
            field=models.CharField(choices=[('single', 'Single Unit'), ('box', 'Box'), ('mm', 'mm')], default='single', max_length=10),
        ),
    ]
