# Generated by Django 4.2.3 on 2023-08-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0005_rename_sku_item_reference_number_item_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='pending', max_length=50),
        ),
    ]
