# Generated by Django 4.2.3 on 2023-08-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0007_rename_user_inventorylocation_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreLocation',
            new_name='Inventory',
        ),
    ]
