# Generated by Django 4.2.3 on 2023-08-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0008_rename_storelocation_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='assigned_inventory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
