# Generated by Django 4.2.3 on 2023-09-06 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0009_alter_inventory_assigned_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_management.vendor', verbose_name='Vendor'),
        ),
    ]
