# Generated by Django 4.2.3 on 2023-09-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0010_item_vendor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
    ]
