# Generated by Django 4.2.3 on 2023-12-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0011_remove_item_item_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='inventorylocation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='vendorcontactperson',
            options={'ordering': ['id']},
        ),
    ]
