# Generated by Django 4.2.3 on 2024-01-25 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0005_alter_siteaddress_country_alter_siteaddress_county_and_more'),
        ('stock_management', '0014_alter_inventorylocation_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='site_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_management.siteaddress'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_management.inventorylocation'),
        ),
    ]
