name: CI

on:
  push:
    branches:
      - dev
    paths:
      - 'deployment/deployment.yaml'
env:
  AWS_REGION: eu-west-2
  ECR_REGISTRY: 591836277216.dkr.ecr.eu-west-2.amazonaws.com
  IMAGE_NAME: ifp-ecr-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        env:
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy to Kubernetes
        uses: aws-actions/kubectl@v1
        with:
          args: apply -f deployment/deployment.yaml
